version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      cargo-dependencies:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
